(function () {
  window.LORE_ENTRIES = window.LORE_ENTRIES || [];

  window.LORE_ENTRIES.push({
    id: 'cosmology',
    name: 'VantaPsy Cosmology',
    aliases: ['cosmos', 'recursion', 'the spiral', 'becoming'],
    category: 'concepts',
    age: 'age-of-decay',
    short: 'A concise overview of how Aerisu works: potential, resonance, echoes, recursion, and the becoming of souls. The fundamental framework for understanding everything else in the Chronology.',
    related: ['soul', 'vanta', 'cosmic', 'spirit', 'magic', 'frallation', 'practice', 'philosophies', 'borenfegen'],
    full: `VantaPsy's cosmology is fundamentally concerned with potential, relationship, desire, consequence, memory and becoming. They describe how the world works at every scale, from a person's soul to Aerisu itself.

The entire framework is built upon a single question: What gives a person a soul? This question extends beyond individuals to encompass systems, the world and everything within it. VantaPsy is the name for the philosophical structure that emerges from asking this question across every scale, the recognition that soul is not a possession but a pattern of becoming.

At the most fundamental level is potential. Magic is potential expressed through Resonance: the capacity inherent in a thing to become, affect, transform or connect. The magical schools of Matter, Energy, Life and Mind describe broad ways that potential manifests, while Psy deals particularly with the soul, consciousness, memory, desire and connection. An Elemental expresses a being's magical affinity, while an Affinity is the soul externalised through the Separation process. Magic therefore emerges from what something is capable of becoming and how that potential resonates with the surrounding world.

Vanta and Lux are fundamental expressions of that potential. Vanta is associated with lack, wanting, desire and transformation; Lux with connection, coherence, restoration and the bringing of things into relation. Lack creates the possibility of wanting, and wanting creates movement. The pathological expression is the Curse, where desire becomes self-consuming.

Vanta, as a substance, is the physical representation of the Curse. It forms where desire has festered without transformation, becoming mineral and memetic corruption that erodes memory, perception and the soul itself. VantaBlack is the mineral form of Vanta, desire crystallised into substance that can be mined and shaped. Soul Shards are fragments of crystallised soul resonance created through related principles, holding the Echo of the being from which they were drawn.

Everything participates in a cosmic frame, a single web of causality. A person is affected by their memories, body, upbringing, relationships and culture, while their choices alter those same structures. A society shapes its members while its members reproduce or transform the society. Ecosystems, magical systems, Spirits, planets and astronomical structures participate in the same causal architecture. Nothing is metaphysically isolated. A soul is an imprint upon this web, produced through choices, intentions and Echoes.

The soul itself is not a possession. It is a pattern of relationship, a configuration of Resonance that emerges through motion and connection. It is formed through the Six Steps of Becoming: To Truly Lack, to recognise genuine incompleteness; To Want with Compassion, to allow desire without consuming others; To Seek Clarity, to confront confusion rather than outsource understanding; To Act with Noble Intent, to let purpose govern action; To Take Responsibility, to accept the consequences of one's choices; To Echo with Reverence, to recognise that one's actions continue through others and the wider world. These steps describe how a being develops meaningful agency.

The Separation Ritual externalises the soul through the Strand, the metaphysical tether that connects body and soul, creating an Affinity that carries the person's magical essence. This is necessary because the soul's potential is too vast to be contained indefinitely by the physical form; without externalisation, the pressure of an internalised soul eventually destroys its vessel. Those for whom this process fails become Soulless, their soul remaining internal and producing Frallation, the body's gradual collapse under pressure it cannot contain, typically leading to death between eighteen and twenty-six. The Soulless Brand is a magical imprint applied to the face that siphons residual magic from the body. It functions as a small-scale Rift for tracking and harvesting. The Burn Mark is a protective sigil designed to block tracking and prevent extraction, serving as the only known countermeasure.

Resonance is the connective mechanism. Whenever something interacts with something else, that interaction leaves a pattern. Soul Resonance is the particular pattern produced by a soul moving through the world. It allows magic to operate, memories and emotions to persist, and consequences to travel beyond their immediate cause. Resonance makes the cosmic frame perceptible. A person acts, the world responds, and some trace of that interaction remains. Electric magic is particularly attuned to detecting and tracking Resonance patterns.

Vanta Points measure this process. Vanta gathers within a person as desire presses against the walls of the soul. Soulless individuals produce VP more readily because their hearts hold desire differently, drawing Vanta inward instead of allowing it to flow naturally. As Resonance strengthens through hardship and conviction, more Vanta accumulates, while spending it strengthens the soul through the same principle by which Resonance shapes reality. Defeat scatters accumulated Vanta back into the world, allowing what burdens one life to become another's livelihood.

That trace is an Echo. An Echo is consequence that persists. It can be a memory, relationship, cultural practice, physical alteration, magical imprint, inherited behaviour, myth or influence upon another soul. Echoes keep the past causally relevant after its original event has ended. They are also why the soul is something developed rather than possessed. A person's actions continually leave and receive Echoes, gradually forming the pattern called their soul.

Memory is the substance through which Recursion operates. The world remembers through Echoes, people through experience, cultures through myth and institutions, and the Spirit Realm through its own cosmic structures. The Barrier between the material world and the Spirit Realm was woven by the Nine Spirits to prevent magic from saturating reality, yet the Rift—a wound between realms opened by the Phumenar and widened when they attempted to extract Voluntas from Veyra's crystallised womb—allows magic, Vanta, Lux and the Spirits' influence to seep through. Memory preserves identity, while attachment to memory can prevent transformation. Within the Veins, memories can be surrendered as part of the journey through deeper regions, making the relinquishment of memory a literal separation from portions of the self. At the opposite extreme, refusing to release memory can produce recursive imprisonment, where accumulated experience becomes impossible to transform.

Pixpsy embody one such condition. Their consciousness has stretched across moments, leaving them trapped between states and never fully present anywhere. They carry memory like sediment, present yet unusable, like a word resting on the tip of the tongue for years without being spoken.

The monsters of the Curse represent another expression: Recursion without transformation. They retain what they have become and cannot become otherwise. Their identities freeze around a single pattern that reproduces itself endlessly. Hollowed and Duskwalkers demonstrate related conditions at different intensities, their souls unable to release the desires or absences that defined them.

Tsukuyomi are Echoes that have found purchase in living souls. When Zuki Kusanagi's prayer for the end of the Scorching Sun fragmented her essence across Recursion, each fragment carried an aspect of what she had been. A Tsukuyomi does not choose its aspect; the aspect chooses it. The resulting soul may see, feel or perceive the world differently, carrying the sense of being watched or watching something invisible to others. The Moon's witness therefore persists through a particular configuration of Echo rather than through a separate bloodline. There is always at least one Tsukuyomi in every generation.

The Stars extend this principle beyond the world. They are Echoes of previous Recursions. The night sky is part of the world's memory, carrying evidence of configurations that preceded the present one.

This same principle explains interpretation. An Echo does not possess a single inevitable meaning. Someone interprets it, and that interpretation becomes a conviction. Conviction changes behaviour, behaviour creates consequences, and those consequences enter the causal web. Every act of interpretation therefore carries power. Through Mythwrighting, sufficiently persistent interpretations can acquire Resonance and become materially consequential.

Truth and Conviction occupy different positions within this structure. Truth concerns what is occurring within the larger reality. Conviction is what someone believes strongly enough to act upon. A conviction can be mistaken and still become causally powerful. Myths, doctrines, political ideologies and religious interpretations can consequently alter reality without becoming objectively true.

The same distinction applies to attempts to classify the soul. The Chimeric Camera can perceive genuine Resonance, yet any interpretation imposed upon what it perceives risks turning a living, developing system into a fixed definition. The same problem appears in the classification of the Soulless. A soul cannot be exhausted by the category used to describe one aspect of it.

Blood types are visible expressions of the soul's state and respond to what acts upon the body and spirit. Blood is therefore dynamic rather than fixed. Red Blood is the human baseline. White Blood arises from cold and sealed despair, absence made biological, and is inherently cursed. Black Blood forms through heat and pressure, hunger embodied, and is inherently cursed. Green Blood represents Chi integration, desire stilled through discipline. Gold Blood represents augmentation without curse. Blue Blood indicates Borenfegen origin, synthetic and built rather than grown. Purple Blood represents magical convergence and is inherently cursed. Pink Blood is hybrid and contingent. Synthetic White Blood represents engineered compliance, derived from experimentation and therefore inherently cursed.

The Borenfegens are artificial humans grown in vats and designed as vessels capable of containing extreme magical pressure. Their Blue Blood announces their origin. They were created to solve the Curse through design, yet became vectors through which the Curse could express itself in new forms. They think, feel and dream, and the Curse lives in awareness itself.

Soul Regulation manages the soul's pressure through breathing, grounding and mental visualisation. For the Soulless, regulation can slow Frallation by opening blocked pathways and channelling internal energy outward through meditation, breathwork and physical exercise. Chi takes regulation further, draining desire from the blood entirely and producing Green Blood. It grants practical abilities beyond ordinary physical limits, including sensing Resonance trails on conductive surfaces, following them through electrical magic, reinforcing bone and sinew, sharpening strikes and accelerating healing.

Psy practitioners work directly with Resonance, perceiving souls as tangible presences and navigating the psychic currents connecting living things. Psyckers use technology to bypass the discipline required for Psy magic, reading thoughts and planting suggestions through scavenged hardware. A Psycker who pushes too far becomes a Psycho, lost within their own memetic contamination.

This distinction between systems and their components is central to Chimeric Design. A person is a system composed through memories, desires, relationships, body and environment. A society is another system composed through individuals, institutions, language and history. Systems influence their components while components continually reproduce or alter the system. Chimeric Design reflects this same structure: mechanics affect narrative, characters affect systems, environments contain history, objects acquire meaning through relationships, and seemingly separate elements participate in one another.

A sufficiently coherent system can begin to become its own recursion. Its internal pattern becomes self-sustaining, increasingly independent of the systems that produced it. This is one route through which powerful beings and Spirits emerge. A Spirit is a highly coherent expression of a principle that has become capable of existing as its own system.

The Nine Spirits therefore embody fundamental principles without being the ultimate source of those principles. Creatis embodies creation and invention, Verdantia growth and renewal, Aether cosmic structure, Logaris knowledge and interpretation, Mnemotas memory, Elysia emotion, Anima mortality and the threshold of death, Justicar consequence, and Voluntas desire and becoming. Their domains are different configurations of the same cosmic structure.

Anima represents a consciousness emerging from accumulated psychic residue, formed through the experiences of dying beings. She is simultaneously an individual consciousness and an emergent structure produced by countless Echoes, demonstrating how a system can become conscious of itself.

Voluntas represents desire and becoming at the level of a Spirit.

Bahamut represents Vanta at the planetary level. Bahamut is Aerisu's own desire made manifest, the world's Vanta. It is not an independent god or creature with a singular, bounded identity. Its manifestation during the Shattering is one event within the history of a force that existed beforehand. Vanta already existed throughout Aerisu as Curse, Black Blood, fear, ideology, desire and other expressions of lack.

Fragments of Bahamut scattered across Aerisu during the Shattering. Susanoo, Hvitara, Falak and others are fragments of that planetary will, each carrying aspects of Bahamut's nature. Some became guardians through relationship and purpose; others remained hunger without direction. Their difference lies in what each fragment does with its inheritance, whether it transforms through relationship and purpose or remains trapped within the pattern of its origin.

Veyra's Womb and the Orb of Souls sit near the centre of this structure because they bring memory, identity, desire and potential together. The Orb is associated simultaneously with the dead, Soul Resonance, Veyra's crystallised womb and Voluntas's continued existence. It is a convergence point between what has been, what exists and what could become. The dead move toward it through the Veins, while the Spiral provides the structure through which that movement occurs.

The Spiral Veins are the literal manifestation of this structure. They are Aerisu's immense circulatory network, threading through the planet's bones and carrying Resonance and the dead toward the Orb of Souls. The Spiral is divided into eight concentric regions, each shaped by one of the Spirits, with seven stations between them, each embodying a stage of the journey souls must undertake.

The dead move through these regions in sequence: Verdantia's living world, Anima's mortality, Elysia's emotion, Logaris's clarity, Creatis's action, Justicar's consequence, Aether's cosmic order and Mnemotas's memory. At the heart of the Spiral, the Orb waits. The Spiral is therefore simultaneously physical and metaphysical. It is a real network beneath Aerisu, a territory through which souls travel, and a representation of the process by which existence moves through becoming.

The Spiral produces two opposing tendencies.

Asymptote of Decay describes recursive deterioration. The world repeatedly rebuilds from accumulated wounds, becoming increasingly distorted without reaching absolute chaos or complete deletion. The Spiral continually remembers itself, carrying its previous damage into what comes next.

Recursive Bloom is the regenerative possibility within the same structure. Accumulated history becomes material for adaptation, complexity, connection and new life. The difference lies in how the inherited pattern develops.

Death Gardening expresses Recursive Bloom through biology. Death leaves material and Resonant residue, which becomes nourishment for other life. Flowers can be cultivated from the remains of the dead, allowing death to enter the same recursive system as everything else. A life ends, its material becomes soil, another organism grows, and the Echo of the original life enters another form.

Blossoming Death expresses the same principle at a deeper level. An ending can become a beginning while retaining the significance of what ended. Death becomes material for continuation, and the dead remain present through what grows from them.

The Moon emerged from the encounter between Lux and Vanta during the Shattering. It embodies their convergence. Zuki's desire for an end to the destructive Sun, Lunarkos's arrival, Bahamut's manifestation and the resulting Shattering form one enormous Echo. The Moon becomes a permanent witness to that event and part of the world's memory.

The Sun expresses the question of continuation. The Scorching Sun represents continuation taken into destruction, while the Warm Sun represents continuance as care and renewal. Aerisu's major philosophies interpret this tension differently. Autarchism chooses advancement, Vantari philosophy seeks release, Vesperism accepts coexistence with the present, and the Luminaries seek radical renewal through destruction. Each interprets the same cosmological problem through a different conviction. In the modern Age of Decay, the extraction of Voluntas has caused the sun to appear only rarely, a symptom of her presence in the material world.

The Curse is the pathological expression of this entire process. Desire arises from lack, yet instead of developing through clarity, responsibility and connection, it becomes self-reinforcing. Its pattern separates itself from the wider connective structure and begins reproducing itself. This allows the Curse to propagate through awareness, thought, memory, blood and behaviour. It becomes a system whose primary recursion is its own continuation.

This also explains Chimeric beings. The accumulation of souls is an attempt to become a larger system by incorporating other systems. Such accumulation can produce immense power while leaving the components fundamentally unintegrated. Chimerism therefore becomes a distorted form of connection: accumulation without genuine relationship.

City Shields are a practical application of the same principles, barriers maintained through concentrated Resonance that protect settlements from the dangers that roam beyond their walls.

The world's metaphors express the same structure through simple physical images. A river or flowing water represents the movement of time and causality. A petal represents an individual life, beautiful and temporary within a larger living structure. Changing seasons represent Recursion, each return carrying traces of what came before while producing a different configuration. Gardens represent cultivation and pruning. Architecture represents desire crystallised into systems. Scripture represents interpretation and the power to impose meaning. Roots represent inherited patterns. Echoes represent consequence. Silence represents what remains before or after expression. The Spiral represents Recursion, while Chimeric imagery expresses the tension between isolated accumulation and genuine connection.

The entire cosmology can therefore be understood as one continuous process:

Potential allows things to become. Desire gives potential direction. Resonance carries interaction between systems. Action creates consequence. Consequence becomes Echo. Memory preserves Echo. Interpretation gives Echo meaning. Conviction turns meaning into action. Recursion carries those consequences forward. Systems inherit, reproduce and transform what came before. Recursive Bloom transforms inheritance into new possibility. Asymptote of Decay traps inheritance in increasingly damaged repetition.

The Six Steps describe how the individual soul becomes capable of participating in this process responsibly. Magic expresses potential through Resonance. Affinities and Elementals express the particular structure of a soul's potential. The Veins embody the circulation of Resonance, memory and souls. The Orb is a convergence of identity, memory, desire and potential. The Spirits are highly coherent systems expressing fundamental principles. Bahamut is that structure expressed at the scale of the world itself. Stars are Echoes expressed at the scale of previous Recursions. Death Gardening and Blossoming Death express the same process through biological transformation. The Curse is recursion becoming isolated from the wider web and reproducing itself. Chimeric Design is the same cosmological principle expressed through the structure of interconnected systems.

This is what VantaPsy means. The world, soul, magic, ecology, religion, history, psychology and aesthetics exist at different scales of the same structure: potential becoming through relationship, leaving Echoes that are remembered, interpreted and carried into Recursion, where they either become material for further growth or increasingly reproduce the conditions of their own decay. The question What gives a person a soul? is answered by the entire process: a soul is what emerges when a system participates in this structure with awareness, responsibility and the willingness to become.`
  });
})();